In [60]:
import numpy as np

# data is a Nx3 matrix
data = np.matrix('1 2 3; 4 5 6; 7 8 9; 10 11 12')
M = data.mean(axis=1)
print(data)
Z = data - np.kron(np.ones((1,np.shape(data)[1])), M) # zero mean
print(Z)
C = Z*np.transpose(Z)/(np.shape(data)[1] * 1.0) # covariance matrix
print(C)
[U,S,V] = np.linalg.svd(C) # singular value decomposition getting rotation U and V
data_rotated = V * Z # rotated data, we use V to rotate
data_reduced = data_rotated[:, 0:2] # keep first 2 components
print(data_reduced)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
[[ 0.66666667  0.66666667  0.66666667  0.66666667]
 [ 0.66666667  0.66666667  0.66666667  0.66666667]
 [ 0.66666667  0.66666667  0.66666667  0.66666667]
 [ 0.66666667  0.66666667  0.66666667  0.66666667]]
[[  2.00000000e+00   0.00000000e+00]
 [  4.16333634e-16   0.00000000e+00]
 [  4.44089210e-16   0.00000000e+00]
 [  3.33066907e-16   0.00000000e+00]]
